name: Generate Snake Animation

on:
  schedule: # Execute every 12 hours
     - cron: "* */12 * * *"  # At 6:20 AM and 6:20 PM daily (adjusted for your time preference)
  workflow_dispatch:
  push:
    branches:
      - main  # Assuming your default branch is `main`, change to `master` if needed

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Step 1: Checkout your repository content
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Generate the snake.svg using Platane/snk
      - name: Generate Snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Christian8D
          outputs: dist/snake.svg?palette=github-dark

      # Step 3: Push the generated snake.svg to the `output` branch
      - name: Deploy snake.svg to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
